# Generated by Django 6.0.2 on 2026-03-12 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='b_commission',
        ),
        migrations.RemoveField(
            model_name='product',
            name='c_commission',
        ),
        migrations.RemoveField(
            model_name='product',
            name='d_commission',
        ),
    ]
