# Generated by Django 6.0.2 on 2026-02-26 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='reference',
            field=models.CharField(editable=False, max_length=100, unique=True),
        ),
    ]
