# Generated by Django 6.0.2 on 2026-02-25 10:15

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('investments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamLevel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('level_code', models.CharField(choices=[('B', 'Level B - 10%'), ('C', 'Level C - 6%'), ('D', 'Level D - 3%')], max_length=1, unique=True)),
                ('commission_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('min_referrals', models.IntegerField(default=0)),
                ('min_team_volume', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['level_code'],
            },
        ),
        migrations.CreateModel(
            name='TeamStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_referrals', models.IntegerField(default=0)),
                ('level_1_count', models.IntegerField(default=0)),
                ('level_2_count', models.IntegerField(default=0)),
                ('level_3_count', models.IntegerField(default=0)),
                ('active_referrals', models.IntegerField(default=0)),
                ('level_1_volume', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('level_2_volume', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('level_3_volume', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('team_volume', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('personal_volume', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('total_commission_earned', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('pending_commission', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('level_1_commission', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('level_2_commission', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('level_3_commission', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('current_level', models.CharField(choices=[('B', 'Level B - 10%'), ('C', 'Level C - 6%'), ('D', 'Level D - 3%')], default='B', max_length=1)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='team_stats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-team_volume'],
            },
        ),
        migrations.CreateModel(
            name='TeamCommission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('level', models.CharField(choices=[('B', 'Level B - 10%'), ('C', 'Level C - 6%'), ('D', 'Level D - 3%')], max_length=1)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('paid_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commissions_generated', to=settings.AUTH_USER_MODEL)),
                ('investment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commissions', to='investments.investment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commissions_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'from_user', 'investment', 'level')},
            },
        ),
        migrations.CreateModel(
            name='TeamTree',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('depth', models.IntegerField()),
                ('ancestor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_descendants', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_nodes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['ancestor', 'depth'], name='team_teamtr_ancesto_a2a92d_idx'), models.Index(fields=['user'], name='team_teamtr_user_id_6895b0_idx')],
                'unique_together': {('user', 'ancestor')},
            },
        ),
    ]
