# Generated by Django 6.0.2 on 2026-03-18 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamstats',
            name='bonus_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='teamstats',
            name='total_bonus_earned',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
